--- @class balatro.Game
--- @field ACHIEVEMENTS balatro.Game.AchievementList

--- @class balatro.Game.AchievementList: { [string]: balatro.Game.Achievement }
--- @field _100000k balatro.Game.Achievement
--- @field _1000k balatro.Game.Achievement
--- @field _10k balatro.Game.Achievement
--- @field ante_up balatro.Game.Achievement
--- @field ante_upper balatro.Game.Achievement
--- @field astronomy balatro.Game.Achievement
--- @field big_hands balatro.Game.Achievement
--- @field card_discarder balatro.Game.Achievement
--- @field card_player balatro.Game.Achievement
--- @field cartomancy balatro.Game.Achievement
--- @field clairvoyance balatro.Game.Achievement
--- @field completionist balatro.Game.Achievement
--- @field completionist_plus balatro.Game.Achievement
--- @field completionist_plus_plus balatro.Game.Achievement
--- @field extreme_couponer balatro.Game.Achievement
--- @field flushed balatro.Game.Achievement
--- @field heads_up balatro.Game.Achievement
--- @field high_stakes balatro.Game.Achievement
--- @field legendary balatro.Game.Achievement
--- @field low_stakes balatro.Game.Achievement
--- @field mid_stakes balatro.Game.Achievement
--- @field nest_egg balatro.Game.Achievement
--- @field retrograde balatro.Game.Achievement
--- @field roi balatro.Game.Achievement
--- @field royale balatro.Game.Achievement
--- @field rule_bender balatro.Game.Achievement
--- @field rule_breaker balatro.Game.Achievement
--- @field shattered balatro.Game.Achievement
--- @field speedrunner balatro.Game.Achievement
--- @field tiny_hands balatro.Game.Achievement
--- @field you_get_what_you_get balatro.Game.Achievement

--- @class balatro.Game.Achievement
--- @field earned boolean
--- @field order number
--- @field steamid string
--- @field tier number
