--- @class balatro.Game
--- @field GAME balatro.Game.Current

--- @class balatro.Game.Current: { [string]: any }
--- @field bankrupt_at number
--- @field banned_keys string[]
--- @field base_reroll_cost number
--- @field blind balatro.Blind
--- @field blind_on_deck BlindType
--- @field bosses_used table<string, number>
--- @field cards_played table<Rank, balatro.Game.Current.CardPlayed>
--- @field chips number
--- @field chips_text string
--- @field consumeable_buffer number
--- @field consumeable_usage table<string, balatro.Game.Current.Usage>
--- @field consumeable_usage_total balatro.Game.Current.UsageAll
--- @field current_boss_streak number
--- @field current_round balatro.Game.Current.CurrentRound
--- @field discount_percent number
--- @field dollars number
--- @field ecto_minus number
--- @field edition_rate number
--- @field first_shop_buffoon boolean
--- @field hand_usage table<string, { count: number, order: PokerHand }>
--- @field hands table<PokerHand, balatro.Game.Current.Hand>
--- @field hands_played number
--- @field inflation number
--- @field interest_amount number
--- @field interest_cap number
--- @field joker_buffer number
--- @field joker_rate number
--- @field joker_usage table
--- @field last_blind { boss: boolean, name: string }
--- @field last_hand_played PokerHand
--- @field last_tarot_planet string
--- @field max_jokers number
--- @field modifiers table
--- @field orbital_choices table<number, table<BlindType, PokerHand>>
--- @field pack_size number
--- @field perishable_rounds number
--- @field perscribed_bosses table<number, balatro.Item.Blind>
--- @field planet_rate number
--- @field playind_card_rate number
--- @field pool_flags table
--- @field previous_round balatro.Game.Current.PreviousRound
--- @field probabilities balatro.Game.Current.Probabilities
--- @field pseudorandom balatro.Game.Current.Pseudorandom
--- @field rental_rate number
--- @field round number
--- @field round_bonus balatro.Game.Current.RoundBonus
--- @field round_resets balatro.Game.Current.RoundResets
--- @field round_scores balatro.Game.Current.RoundScores
--- @field seeded boolean
--- @field selected_back balatro.Back
--- @field selected_back_key balatro.Item.Back
--- @field shop balatro.Game.Current.Shop
--- @field skips number
--- @field sort balatro.CardArea.Sort
--- @field spectral_rate number
--- @field stake number
--- @field starting_deck_size number
--- @field starting_params balatro.Game.Current.StartingParam
--- @field subhash string
--- @field tag_tally number
--- @field tags balatro.Tag[]
--- @field tarot_rate number
--- @field unused_discards number
--- @field used_jokers table<string, boolean>
--- @field used_vouchers table<string, boolean>
--- @field voucher_text string
--- @field win_ante number
--- @field won boolean
--- @field STOP_USE? number
--- @field starting_voucher_count? number
--- @field shop_free? boolean
--- @field shop_d6ed? boolean

--- @class balatro.Game.Current.CardPlayed
--- @field suits table<Suit, boolean>
--- @field total number

--- @class balatro.Game.Current.Usage
--- @field count number
--- @field order number
--- @field set string

--- @class balatro.Game.Current.UsageAll
--- @field all number
--- @field planet number
--- @field spectral number
--- @field tarot number
--- @field tarot_planet number

--- @class balatro.Game.Current.CurrentRound: { [string]: any }
--- @field ancient_card { suit: Suit }
--- @field castle_card { suit: Suit }
--- @field idol_card { id: number, rank: Rank, suit: Suit }
--- @field cards_flipped number
--- @field current_hand balatro.Game.Current.CurrentRound.CurrentHand
--- @field discards_left number
--- @field discards_used number
--- @field dollars number
--- @field dollars_to_be_earned number | ''
--- @field free_rerolls number
--- @field hands_left number
--- @field hands_played number
--- @field jokers_purchased number
--- @field mail_card { id: number, rank: Rank }
--- @field most_played_poker_hand PokerHand
--- @field reroll_cost number
--- @field reroll_cost_increase number
--- @field round_dollars number
--- @field round_text string
--- @field used_packs table<number, string>
--- @field voucher string

--- @class balatro.Game.Current.CurrentRound.CurrentHand: { [string]: any }
--- @field chip_text string
--- @field chip_total number
--- @field chip_total_text string
--- @field chips number
--- @field hand_level number | ""
--- @field handname string
--- @field handname_text string
--- @field mult number
--- @field mult_text string

--- @class balatro.Game.Current.Hand: { [string]: any }
--- @field chips number
--- @field example [string, boolean][]
--- @field l_chips number
--- @field l_mult number
--- @field level number
--- @field mult number
--- @field order number
--- @field played number
--- @field played_this_round number
--- @field s_chips number
--- @field s_mult number
--- @field visible boolean

--- @class balatro.Game.Current.PreviousRound
--- @field dollars number

--- @class balatro.Game.Current.Probabilities: {[string]: number}
--- @field normal number

--- @class balatro.Game.Current.Pseudorandom: {[string]: number}
--- @field seed string

--- @class balatro.Game.Current.RoundBonus
--- @field discards number
--- @field next_hands number

--- @class balatro.Game.Current.Shop
--- @field joker_max number

--- @class balatro.Game.Current.RoundResets: { [string]: any }
--- @field ante number
--- @field blind balatro.Item.Blind
--- @field blind_ante number
--- @field blind_choices table<BlindType, string>
--- @field blind_states table<BlindType, BlindState>
--- @field blind_tags table<'Big' | 'Small', string>
--- @field boss_rerolled boolean
--- @field discards number
--- @field hands number
--- @field loc_blind_states table<BlindType, string>
--- @field reroll_cost number

--- @class balatro.Game.Current.RoundScores: {[string]: balatro.Profile.HighScore}
--- @field cards_discarded balatro.Profile.HighScore
--- @field cards_played balatro.Profile.HighScore
--- @field cards_purchased balatro.Profile.HighScore
--- @field furthest_ante balatro.Profile.HighScore
--- @field furthest_round balatro.Profile.HighScore
--- @field hand balatro.Profile.HighScore
--- @field new_collection balatro.Profile.HighScore
--- @field poker_hand balatro.Profile.HighScore
--- @field times_rerolled balatro.Profile.HighScore

--- @class balatro.Game.Current.StartingParam: { [string]: any }
--- @field ante_scaling number
--- @field consumable_slots number
--- @field discards number
--- @field dollars number
--- @field erratic_suits_and_ranks boolean
--- @field hand_size number
--- @field hands number
--- @field joker_slots number
--- @field no_faces boolean
--- @field reroll_cost number
