--- @class balatro.Game: balatro.Game.UIs

--- @class balatro.Game.UIs
--- @field buttons? balatro.UIBox
--- @field deck_preview? balatro.UIBox
--- @field shop? balatro.UIBox
--- @field blind_select? balatro.UIBox
--- @field booster_pack? balatro.UIBox
--- @field MAIN_MENU_UI? balatro.UIBox
--- @field SPLASH_FRONT? balatro.UIBox
--- @field SPLASH_BACK? balatro.UIBox
--- @field SPLASH_LOGO? balatro.UIBox
--- @field GAME_OVER_UI? balatro.UIBox
--- @field collection_alert? balatro.UIBox
--- @field HUD? balatro.UIBox
--- @field HUD_blind? balatro.UIBox
--- @field HUD_tags? balatro.UIBox[]
--- @field OVERLAY_MENU? balatro.UIBox
--- @field OVERLAY_TUTORIAL? balatro.UIBox